on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('python/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install depencies
      run: pip install -r python/requirements.txt
    
    - name: Run lint
      run: pylint python/*.py

    - name: Run tests
      run: pytest python/test.py
  
